apiVersion: archiver.kubedb.com/v1alpha1
kind: MongoDBArchiver
metadata:
  name: mongodbarchiver-sample
  namespace: demo
spec:
  pause: false
  databases:
    namespaces:
      from: "Same"
    selector:
      matchLabels:
        archiver: "true"
  retentionPolicy:
    name: mongodb-retention-policy
    namespace: demo
  fullBackup:
    driver: "CSISnapshotter"
    csiSnapshotter:
      volumeSnapshotClassName: "longhorn-snapshot-vsc"
    scheduler:
      schedule: "*/5 * * * *"
  manifestBackup:
    encryptionSecret:
      name: "encrypt-secret"
      namespace: "demo"
    scheduler:
      schedule: "*/5 * * * *"
  backupStorage:
    ref:
      apiGroup: "storage.kubestash.com"
      kind: "BackupStorage"
      name: "linode-storage"
      namespace: "demo"
                              