apiVersion: storage.kubestash.com/v1alpha1
kind: RetentionPolicy
metadata:
  name: mongodb-retention-policy
  namespace: demo
spec:
  maxRetentionPeriod: "30d"
  successfulSnapshots:
    last: 100
    hourly: 12
    daily: 100
    weekly: 1000
    monthly: 5000
    yearly: 100000
  failedSnapshots:
    last: 5
